"use client";

import {
  createContext,
  useContext,
  useState,
  useEffect,
  ReactNode,
} from "react";

export type Language = "en" | "es" | "fr" | "de" | "ja" | "ko" | "zh" | "ar" | "hi" | "pt";

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    "nav.home": "Home",
    "nav.generate": "Generate",
    "nav.history": "History",
    "nav.pricing": "Pricing",
    "nav.profile": "Profile",
    "nav.signin": "Sign In",
    "nav.signout": "Sign Out",
    "nav.credits": "Credits",
    "nav.themes": "Themes",
    "hero.title": "Create Stunning AI Art",
    "hero.subtitle": "Generate breathtaking images and videos with the power of AI. No expertise needed.",
    "hero.cta.generate": "Start Creating",
    "hero.cta.explore": "Explore Gallery",
    "generate.title": "Create",
    "generate.prompt.placeholder": "Describe what you want to create...",
    "generate.button": "Generate",
    "generate.image": "Image",
    "generate.video": "Video",
    "generate.model": "Model",
    "generate.style": "Style",
    "generate.credits": "credits",
    "history.title": "Your Creations",
    "history.empty": "No creations yet. Start generating!",
    "history.status.pending": "Processing",
    "history.status.completed": "Complete",
    "history.status.failed": "Failed",
    "pricing.title": "Choose Your Plan",
    "pricing.free": "Free",
    "pricing.pro": "Pro",
    "pricing.enterprise": "Enterprise",
    "pricing.cta": "Get Started",
    "profile.title": "Profile",
    "profile.credits": "Available Credits",
    "profile.totalCreations": "Total Creations",
    "footer.about": "About",
    "footer.contact": "Contact",
    "footer.faq": "FAQ",
    "footer.privacy": "Privacy",
    "footer.terms": "Terms",
    "auth.signin": "Sign In",
    "auth.email": "Email",
    "auth.code": "Verification Code",
    "auth.sendCode": "Send Code",
    "auth.verify": "Verify",
    "auth.sent": "Code sent! Check your email.",
    "theme.title": "Select Theme",
    "lang.title": "Language",
  },
  es: {
    "nav.home": "Inicio",
    "nav.generate": "Generar",
    "nav.history": "Historial",
    "nav.pricing": "Precios",
    "nav.profile": "Perfil",
    "nav.signin": "Iniciar Sesin",
    "nav.signout": "Cerrar Sesin",
    "nav.credits": "Crditos",
    "nav.themes": "Temas",
    "hero.title": "Crea Arte AI Asombroso",
    "hero.subtitle": "Genera imgenes y videos impresionantes con el poder de la IA. No se necesita experiencia.",
    "hero.cta.generate": "Comenzar a Crear",
    "hero.cta.explore": "Explorar Galera",
    "generate.title": "Crear",
    "generate.prompt.placeholder": "Describe lo que quieres crear...",
    "generate.button": "Generar",
    "generate.image": "Imagen",
    "generate.video": "Video",
    "generate.model": "Modelo",
    "generate.style": "Estilo",
    "generate.credits": "crditos",
    "history.title": "Tus Creaciones",
    "history.empty": "Aun no hay creaciones. Empieza a generar!",
    "history.status.pending": "Procesando",
    "history.status.completed": "Completo",
    "history.status.failed": "Fallido",
    "pricing.title": "Elige Tu Plan",
    "pricing.free": "Gratis",
    "pricing.pro": "Pro",
    "pricing.enterprise": "Empresarial",
    "pricing.cta": "Comenzar",
    "profile.title": "Perfil",
    "profile.credits": "Crditos Disponibles",
    "profile.totalCreations": "Total de Creaciones",
    "footer.about": "Acerca de",
    "footer.contact": "Contacto",
    "footer.faq": "Preguntas",
    "footer.privacy": "Privacidad",
    "footer.terms": "Trminos",
    "auth.signin": "Iniciar Sesin",
    "auth.email": "Correo",
    "auth.code": "Cdigo de Verificacin",
    "auth.sendCode": "Enviar Cdigo",
    "auth.verify": "Verificar",
    "auth.sent": "Cdigo enviado! Revisa tu correo.",
    "theme.title": "Seleccionar Tema",
    "lang.title": "Idioma",
  },
  fr: {
    "nav.home": "Accueil",
    "nav.generate": "Gnrer",
    "nav.history": "Historique",
    "nav.pricing": "Tarifs",
    "nav.profile": "Profil",
    "nav.signin": "Connexion",
    "nav.signout": "Dconnexion",
    "nav.credits": "Crédits",
    "nav.themes": "Thèmes",
    "hero.title": "Cre des Oeuvres d'IA Époustouflantes",
    "hero.subtitle": "Gnère des images et vidéos saisissantes avec la puissance de l'IA. Aucune expertise requise.",
    "hero.cta.generate": "Commencer  Créer",
    "hero.cta.explore": "Explorer la Galerie",
    "generate.title": "Créer",
    "generate.prompt.placeholder": "Décris ce que tu veux créer...",
    "generate.button": "Gnrer",
    "generate.image": "Image",
    "generate.video": "Vido",
    "generate.model": "Modèle",
    "generate.style": "Style",
    "generate.credits": "crédits",
    "history.title": "Tes Créations",
    "history.empty": "Pas encore de créations. Commence  générer!",
    "history.status.pending": "En cours",
    "history.status.completed": "Termin",
    "history.status.failed": "Chou",
    "pricing.title": "Choisis Ton Plan",
    "pricing.free": "Gratuit",
    "pricing.pro": "Pro",
    "pricing.enterprise": "Entreprise",
    "pricing.cta": "Commencer",
    "profile.title": "Profil",
    "profile.credits": "Crédits Disponibles",
    "profile.totalCreations": "Total de Créations",
    "footer.about": "Propos",
    "footer.contact": "Contact",
    "footer.faq": "FAQ",
    "footer.privacy": "Confidentialité",
    "footer.terms": "Conditions",
    "auth.signin": "Connexion",
    "auth.email": "Email",
    "auth.code": "Code de Vérification",
    "auth.sendCode": "Envoyer le Code",
    "auth.verify": "Vérifier",
    "auth.sent": "Code envoy! Vérifie ton email.",
    "theme.title": "Choisir un Thème",
    "lang.title": "Langue",
  },
  de: {
    "nav.home": "Startseite",
    "nav.generate": "Generieren",
    "nav.history": "Verlauf",
    "nav.pricing": "Preise",
    "nav.profile": "Profil",
    "nav.signin": "Anmelden",
    "nav.signout": "Abmelden",
    "nav.credits": "Credits",
    "nav.themes": "Themen",
    "hero.title": "Erstelle Atemberaubende KI-Kunst",
    "hero.subtitle": "Generiere atemberaubende Bilder und Videos mit der Kraft von KI. Keine Expertise erforderlich.",
    "hero.cta.generate": "Jetzt Erstellen",
    "hero.cta.explore": "Galerie Erkunden",
    "generate.title": "Erstellen",
    "generate.prompt.placeholder": "Beschreibe, was du erstellen möchtest...",
    "generate.button": "Generieren",
    "generate.image": "Bild",
    "generate.video": "Video",
    "generate.model": "Modell",
    "generate.style": "Stil",
    "generate.credits": "Credits",
    "history.title": "Deine Kreationen",
    "history.empty": "Noch keine Kreationen. Fang an zu generieren!",
    "history.status.pending": "Wird verarbeitet",
    "history.status.completed": "Abgeschlossen",
    "history.status.failed": "Fehlgeschlagen",
    "pricing.title": "Wähle Deinen Plan",
    "pricing.free": "Kostenlos",
    "pricing.pro": "Pro",
    "pricing.enterprise": "Enterprise",
    "pricing.cta": "Loslegen",
    "profile.title": "Profil",
    "profile.credits": "Verfügbare Credits",
    "profile.totalCreations": "Gesamte Kreationen",
    "footer.about": "Über uns",
    "footer.contact": "Kontakt",
    "footer.faq": "FAQ",
    "footer.privacy": "Datenschutz",
    "footer.terms": "AGB",
    "auth.signin": "Anmelden",
    "auth.email": "Email",
    "auth.code": "Verifizierungscode",
    "auth.sendCode": "Code senden",
    "auth.verify": "Verifizieren",
    "auth.sent": "Code gesendet! Prüfe deine Email.",
    "theme.title": "Thema auswählen",
    "lang.title": "Sprache",
  },
  ja: {
    "nav.home": "ホーム",
    "nav.generate": "生成",
    "nav.history": "履歴",
    "nav.pricing": "料金",
    "nav.profile": "プロフィール",
    "nav.signin": "ログイン",
    "nav.signout": "ログアウト",
    "nav.credits": "クレジット",
    "nav.themes": "テーマ",
    "hero.title": "AIアートを作成",
    "hero.subtitle": "AIの力で素晴らしい画像と動画を生成。専門知識は不要。",
    "hero.cta.generate": "作成を開始",
    "hero.cta.explore": "ギャラリーを探索",
    "generate.title": "作成",
    "generate.prompt.placeholder": "作成したいものを説明...",
    "generate.button": "生成",
    "generate.image": "画像",
    "generate.video": "動画",
    "generate.model": "モデル",
    "generate.style": "スタイル",
    "generate.credits": "クレジット",
    "history.title": "あなたの作品",
    "history.empty": "まだ作品がありません。生成を開始！",
    "history.status.pending": "処理中",
    "history.status.completed": "完了",
    "history.status.failed": "失敗",
    "pricing.title": "プランを選択",
    "pricing.free": "無料",
    "pricing.pro": "Pro",
    "pricing.enterprise": "Enterprise",
    "pricing.cta": "始める",
    "profile.title": "プロフィール",
    "profile.credits": "利用可能クレジット",
    "profile.totalCreations": "総作品数",
    "footer.about": "概要",
    "footer.contact": "お問い合わせ",
    "footer.faq": "FAQ",
    "footer.privacy": "プライバシー",
    "footer.terms": "規約",
    "auth.signin": "ログイン",
    "auth.email": "メール",
    "auth.code": "認証コード",
    "auth.sendCode": "コード送信",
    "auth.verify": "確認",
    "auth.sent": "コード送信済み！メールを確認。",
    "theme.title": "テーマを選択",
    "lang.title": "言語",
  },
  ko: {
    "nav.home": "홈",
    "nav.generate": "생성",
    "nav.history": "기록",
    "nav.pricing": "가격",
    "nav.profile": "프로필",
    "nav.signin": "로그인",
    "nav.signout": "로그아웃",
    "nav.credits": "크레딧",
    "nav.themes": "테마",
    "hero.title": "AI 아트 생성",
    "hero.subtitle": "AI의 힘으로 멋진 이미지와 영상을 생성하세요. 전문 지식이 필요 없습니다.",
    "hero.cta.generate": "생성 시작",
    "hero.cta.explore": "갤러리 탐색",
    "generate.title": "생성",
    "generate.prompt.placeholder": "생성할 것을 설명하세요...",
    "generate.button": "생성",
    "generate.image": "이미지",
    "generate.video": "영상",
    "generate.model": "모델",
    "generate.style": "스타일",
    "generate.credits": "크레딧",
    "history.title": "내 작품",
    "history.empty": "아직 작품이 없습니다. 생성을 시작하세요!",
    "history.status.pending": "처리 중",
    "history.status.completed": "완료",
    "history.status.failed": "실패",
    "pricing.title": "플랜 선택",
    "pricing.free": "무료",
    "pricing.pro": "Pro",
    "pricing.enterprise": "Enterprise",
    "pricing.cta": "시작하기",
    "profile.title": "프로필",
    "profile.credits": "사용 가능 크레딧",
    "profile.totalCreations": "총 작품 수",
    "footer.about": "소개",
    "footer.contact": "연락처",
    "footer.faq": "FAQ",
    "footer.privacy": "개인정보",
    "footer.terms": "약관",
    "auth.signin": "로그인",
    "auth.email": "이메일",
    "auth.code": "인증 코드",
    "auth.sendCode": "코드 전송",
    "auth.verify": "확인",
    "auth.sent": "코드 전송됨! 이메일을 확인하세요.",
    "theme.title": "테마 선택",
    "lang.title": "언어",
  },
  zh: {
    "nav.home": "首页",
    "nav.generate": "生成",
    "nav.history": "历史",
    "nav.pricing": "定价",
    "nav.profile": "个人资料",
    "nav.signin": "登录",
    "nav.signout": "退出",
    "nav.credits": "积分",
    "nav.themes": "主题",
    "hero.title": "创建AI艺术",
    "hero.subtitle": "利用AI的力量生成令人惊叹的图像和视频。无需专业知识。",
    "hero.cta.generate": "开始创作",
    "hero.cta.explore": "探索画廊",
    "generate.title": "创作",
    "generate.prompt.placeholder": "描述你想创建的内容...",
    "generate.button": "生成",
    "generate.image": "图像",
    "generate.video": "视频",
    "generate.model": "模型",
    "generate.style": "风格",
    "generate.credits": "积分",
    "history.title": "你的作品",
    "history.empty": "还没有作品。开始生成吧！",
    "history.status.pending": "处理中",
    "history.status.completed": "完成",
    "history.status.failed": "失败",
    "pricing.title": "选择方案",
    "pricing.free": "免费",
    "pricing.pro": "专业版",
    "pricing.enterprise": "企业版",
    "pricing.cta": "开始使用",
    "profile.title": "个人资料",
    "profile.credits": "可用积分",
    "profile.totalCreations": "总作品数",
    "footer.about": "关于",
    "footer.contact": "联系",
    "footer.faq": "常见问题",
    "footer.privacy": "隐私",
    "footer.terms": "条款",
    "auth.signin": "登录",
    "auth.email": "邮箱",
    "auth.code": "验证码",
    "auth.sendCode": "发送验证码",
    "auth.verify": "验证",
    "auth.sent": "验证码已发送！请检查邮箱。",
    "theme.title": "选择主题",
    "lang.title": "语言",
  },
  ar: {
    "nav.home": "الرئيسية",
    "nav.generate": "إنشاء",
    "nav.history": "السجل",
    "nav.pricing": "الأسعار",
    "nav.profile": "الملف الشخصي",
    "nav.signin": "تسجيل الدخول",
    "nav.signout": "تسجيل الخروج",
    "nav.credits": "الرصيد",
    "nav.themes": "السمات",
    "hero.title": "إنشاء فن AI مذهل",
    "hero.subtitle": "أنشئ صورًا ومقاطع فيديو مذهلة بقوة الذكاء الاصطناعي. لا حاجة لخبرة.",
    "hero.cta.generate": "ابدأ الإنشاء",
    "hero.cta.explore": "استكشف المعرض",
    "generate.title": "إنشاء",
    "generate.prompt.placeholder": "صف ما تريد إنشاؤه...",
    "generate.button": "إنشاء",
    "generate.image": "صورة",
    "generate.video": "فيديو",
    "generate.model": "النموذج",
    "generate.style": "الأسلوب",
    "generate.credits": "رصيد",
    "history.title": "إبداعاتك",
    "history.empty": "لا توجد إبداعات بعد. ابدأ الإنشاء!",
    "history.status.pending": "جاري المعالجة",
    "history.status.completed": "مكتمل",
    "history.status.failed": "فشل",
    "pricing.title": "اختر خطتك",
    "pricing.free": "مجاني",
    "pricing.pro": "Pro",
    "pricing.enterprise": "Enterprise",
    "pricing.cta": "ابدأ",
    "profile.title": "الملف الشخصي",
    "profile.credits": "الرصيد المتاح",
    "profile.totalCreations": "إجمالي الإبداعات",
    "footer.about": "حول",
    "footer.contact": "تواصل",
    "footer.faq": "الأسئلة",
    "footer.privacy": "الخصوصية",
    "footer.terms": "الشروط",
    "auth.signin": "تسجيل الدخول",
    "auth.email": "البريد",
    "auth.code": "رمز التحقق",
    "auth.sendCode": "إرسال الرمز",
    "auth.verify": "تحقق",
    "auth.sent": "تم إرسال الرمز! تحقق من بريدك.",
    "theme.title": "اختر السمة",
    "lang.title": "اللغة",
  },
  hi: {
    "nav.home": "होम",
    "nav.generate": "जेनरेट",
    "nav.history": "इतिहास",
    "nav.pricing": "मूल्य",
    "nav.profile": "प्रोफाइल",
    "nav.signin": "साइन इन",
    "nav.signout": "साइन आउट",
    "nav.credits": "क्रेडिट्स",
    "nav.themes": "थीम्स",
    "hero.title": "AI आर्ट बनाएं",
    "hero.subtitle": "AI की शक्ति से शानदार इमेज और वीडियो जेनरेट करें। कोई विशेषज्ञता नहीं चाहिए।",
    "hero.cta.generate": "बनाना शुरू करें",
    "hero.cta.explore": "गैलरी देखें",
    "generate.title": "बनाएं",
    "generate.prompt.placeholder": "वर्णन करें कि आप क्या बनाना चाहते हैं...",
    "generate.button": "जेनरेट",
    "generate.image": "इमेज",
    "generate.video": "वीडियो",
    "generate.model": "मॉडल",
    "generate.style": "स्टाइल",
    "generate.credits": "क्रेडिट्स",
    "history.title": "आपकी रचनाएं",
    "history.empty": "अभी तक कोई रचना नहीं। बनाना शुरू करें!",
    "history.status.pending": "प्रोसेसिंग",
    "history.status.completed": "पूरा",
    "history.status.failed": "फेल",
    "pricing.title": "प्लान चुनें",
    "pricing.free": "फ्री",
    "pricing.pro": "Pro",
    "pricing.enterprise": "Enterprise",
    "pricing.cta": "शुरू करें",
    "profile.title": "प्रोफाइल",
    "profile.credits": "उपलब्ध क्रेडिट्स",
    "profile.totalCreations": "कुल रचनाएं",
    "footer.about": "हमारे बारे में",
    "footer.contact": "संपर्क",
    "footer.faq": "FAQ",
    "footer.privacy": "प्राइवसी",
    "footer.terms": "नियम",
    "auth.signin": "साइन इन",
    "auth.email": "ईमेल",
    "auth.code": "वेरिफिकेशन कोड",
    "auth.sendCode": "कोड भेजें",
    "auth.verify": "वेरिफाई",
    "auth.sent": "कोड भेज दिया! ईमेल चेक करें।",
    "theme.title": "थीम चुनें",
    "lang.title": "भाषा",
  },
  pt: {
    "nav.home": "Início",
    "nav.generate": "Gerar",
    "nav.history": "Histórico",
    "nav.pricing": "Preços",
    "nav.profile": "Perfil",
    "nav.signin": "Entrar",
    "nav.signout": "Sair",
    "nav.credits": "Créditos",
    "nav.themes": "Temas",
    "hero.title": "Crie Arte IA Incrível",
    "hero.subtitle": "Gere imagens e vídeos impressionantes com o poder da IA. Nenhuma expertise necessária.",
    "hero.cta.generate": "Começar a Criar",
    "hero.cta.explore": "Explorar Galeria",
    "generate.title": "Criar",
    "generate.prompt.placeholder": "Descreva o que você quer criar...",
    "generate.button": "Gerar",
    "generate.image": "Imagem",
    "generate.video": "Vídeo",
    "generate.model": "Modelo",
    "generate.style": "Estilo",
    "generate.credits": "créditos",
    "history.title": "Suas Criações",
    "history.empty": "Sem criações ainda. Comece a gerar!",
    "history.status.pending": "Processando",
    "history.status.completed": "Completo",
    "history.status.failed": "Falhou",
    "pricing.title": "Escolha Seu Plano",
    "pricing.free": "Grátis",
    "pricing.pro": "Pro",
    "pricing.enterprise": "Enterprise",
    "pricing.cta": "Começar",
    "profile.title": "Perfil",
    "profile.credits": "Créditos Disponíveis",
    "profile.totalCreations": "Total de Criações",
    "footer.about": "Sobre",
    "footer.contact": "Contato",
    "footer.faq": "FAQ",
    "footer.privacy": "Privacidade",
    "footer.terms": "Termos",
    "auth.signin": "Entrar",
    "auth.email": "Email",
    "auth.code": "Código de Verificação",
    "auth.sendCode": "Enviar Código",
    "auth.verify": "Verificar",
    "auth.sent": "Código enviado! Verifique seu email.",
    "theme.title": "Selecionar Tema",
    "lang.title": "Idioma",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Language>("en");

  useEffect(() => {
    const saved = localStorage.getItem("8x-lang") as Language | null;
    if (saved && translations[saved]) setLangState(saved);
  }, []);

  const setLang = (l: Language) => {
    setLangState(l);
    localStorage.setItem("8x-lang", l);
    document.documentElement.lang = l;
  };

  const t = (key: string): string => {
    return translations[lang]?.[key] || translations.en?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
}
